ormi5-1poom/idk

src/main/java/team/onepoom/idk/domain/question/Question.java
- resolve #2
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 질문 엔티티 개발

src/main/java/team/onepoom/idk/domain/questionReport/QuestionReport.java
- resolve #14
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 질문 신고 처리일자 필드 추가

src/main/java/team/onepoom/idk/common/exception/ForbiddenException.java, src/main/java/team/onepoom/idk/common/exception/NotFoundException.java, src/main/java/team/onepoom/idk/common/exception/QuestionForbiddenException.java, src/main/java/team/onepoom/idk/common/exception/QuestionNotFoundException.java, src/main/java/team/onepoom/idk/common/exception/UserNotFoundException.java, src/main/java/team/onepoom/idk/config/QuerydslConfig.java, src/main/java/team/onepoom/idk/controller/QuestionController.java, src/main/java/team/onepoom/idk/domain/question/Question.java, src/main/java/team/onepoom/idk/domain/question/dto/CreateQuestionRequest.java, src/main/java/team/onepoom/idk/domain/question/dto/FindQuestionQuery.java, src/main/java/team/onepoom/idk/domain/question/dto/GetQuestionDetailResponse.java, src/main/java/team/onepoom/idk/domain/question/dto/GetQuestionResponse.java, src/main/java/team/onepoom/idk/domain/question/dto/ModifyQuestionRequest.java, src/main/java/team/onepoom/idk/repository/QuestionRepository.java, src/main/java/team/onepoom/idk/repository/QuestionRepositoryCustom.java, src/main/java/team/onepoom/idk/repository/QuestionRepositoryImpl.java, src/main/java/team/onepoom/idk/service/QuestionService.java, src/main/resources/question.http
- resolve #11
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 질문 기능 개발

src/main/java/team/onepoom/idk/controller/AnswerController.java, src/main/java/team/onepoom/idk/domain/answer/Answer.java, src/main/java/team/onepoom/idk/domain/answer/dto/AnswerResponse.java, src/main/java/team/onepoom/idk/domain/answer/dto/CreateAnswerRequest.java, src/main/java/team/onepoom/idk/domain/answer/dto/ModifyAnswerRequest.java, src/main/java/team/onepoom/idk/domain/answer/dto/MyAnswerResponse.java, src/main/java/team/onepoom/idk/repository/AnswerRepository.java, src/main/java/team/onepoom/idk/service/AnswerService.java
=> [Feat] 답변 기능 개발

src/main/java/team/onepoom/idk/domain/answerReport/AnswerReport.java
- resolve #8 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 답변 신고 엔티티 개발

frontend/package-lock.json, frontend/package.json
- resolve #23 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Bug] PostCSS 업데이트

src/main/java/team/onepoom/idk/common/exception/AnswerForbiddenException.java, src/main/java/team/onepoom/idk/common/exception/AnswerNotFoundException.java, src/main/java/team/onepoom/idk/common/exception/SelectedAnswerForbiddenException.java, src/main/java/team/onepoom/idk/controller/AnswerController.java, src/main/java/team/onepoom/idk/domain/answer/Answer.java, src/main/java/team/onepoom/idk/domain/answer/dto/ModifyAnswerRequest.java, src/main/java/team/onepoom/idk/service/AnswerService.java
resolve #21 
PR의 개요를 적어주세요.
답변 커스텀 예외 추가 및 적용
답변수정 dto 재적용
=> [Feat] 답변 예외처리 기능 개발

src/main/java/team/onepoom/idk/controller/QuestionController.java, src/main/java/team/onepoom/idk/domain/question/Question.java, src/main/java/team/onepoom/idk/service/QuestionService.java
- resolve #33 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Bug] 질문 기능 수정

src/main/java/team/onepoom/idk/common/advice/GlobalExceptionAdvice.java, src/main/java/team/onepoom/idk/common/exception/ConflictException.java, src/main/java/team/onepoom/idk/common/response/ErrorResponse.java, src/main/java/team/onepoom/idk/controller/AnswerController.java, src/main/java/team/onepoom/idk/repository/AnswerRepository.java, src/main/java/team/onepoom/idk/service/AnswerService.java, src/main/resources/answer.http
resolve #26 
PR의 개요를 적어주세요.
GlobalExceptionAdvice 추가
ErrorResponse 추가
ConflictException 추가
+ 답변 기능 수정.. 
=> [Feat] 공통 예외처리 기능 개발 .. (+ 답변 기능 수정)

src/main/java/team/onepoom/idk/controller/NoticeController.java, src/main/java/team/onepoom/idk/domain/notice/Notice.java, src/main/java/team/onepoom/idk/domain/notice/NoticeNotFoundException.java, src/main/java/team/onepoom/idk/domain/notice/dto/AllNoticeResponse.java, src/main/java/team/onepoom/idk/domain/notice/dto/CreateNoticeRequest.java, src/main/java/team/onepoom/idk/domain/notice/dto/DetailNoticeResponse.java, src/main/java/team/onepoom/idk/domain/notice/dto/UpdateNoticeRequest.java, src/main/java/team/onepoom/idk/domain/user/User.java, src/main/java/team/onepoom/idk/repository/NoticeRepository.java, src/main/java/team/onepoom/idk/service/NoticeService.java
resolve #13
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 공지사항 기능 개발

src/main/java/team/onepoom/idk/common/exception/NoticeNotFoundException.java, src/main/java/team/onepoom/idk/controller/NoticeController.java, src/main/java/team/onepoom/idk/domain/notice/dto/AllNoticeResponse.java, src/main/java/team/onepoom/idk/domain/notice/dto/CreateNoticeRequest.java, src/main/java/team/onepoom/idk/domain/notice/dto/DetailNoticeResponse.java, src/main/java/team/onepoom/idk/domain/notice/dto/UpdateNoticeRequest.java, src/main/java/team/onepoom/idk/service/NoticeService.java
resolve #37
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Fix] 공지사항 기능 오류 수정

src/main/java/team/onepoom/idk/controller/NoticeController.java, src/main/java/team/onepoom/idk/domain/notice/Notice.java, src/main/java/team/onepoom/idk/domain/notice/dto/DetailNoticeResponse.java, src/main/java/team/onepoom/idk/domain/notice/dto/FiveNoticeResponse.java, src/main/java/team/onepoom/idk/repository/NoticeRepository.java, src/main/java/team/onepoom/idk/service/NoticeService.java
resolve #40
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 공지사항 5개 목록으로 보여주는 기능 개발

src/main/java/team/onepoom/idk/common/exception/ReportReasonNotFoundException.java, src/main/java/team/onepoom/idk/controller/ReportReasonController.java, src/main/java/team/onepoom/idk/domain/reportReason/ReportReason.java, src/main/java/team/onepoom/idk/domain/reportReason/dto/AllReportReasonResponse.java, src/main/java/team/onepoom/idk/domain/reportReason/dto/CreateReportReasonRequest.java, src/main/java/team/onepoom/idk/repository/ReportReasonRepository.java, src/main/java/team/onepoom/idk/service/ReportReasonService.java
resolve #30
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 신고 사유 기능 개발

src/main/java/team/onepoom/idk/domain/question/Question.java
- resolve #28 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 질문 삭제 (관리자)

src/main/java/team/onepoom/idk/domain/answer/Answer.java, src/main/java/team/onepoom/idk/domain/question/Question.java
- resolve #29 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 답변 삭제 (관리자)

src/main/java/team/onepoom/idk/controller/ReportReasonController.java
- resolve #47 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 신고 사유 엔드포인트 변경

src/main/java/team/onepoom/idk/domain/question/Question.java, src/main/java/team/onepoom/idk/domain/question/dto/GetMyQuestionResponse.java, src/main/java/team/onepoom/idk/domain/question/dto/GetQuestionDetailResponse.java, src/main/java/team/onepoom/idk/domain/question/dto/GetQuestionResponse.java, src/main/java/team/onepoom/idk/repository/CustomRepository.java, src/main/java/team/onepoom/idk/service/QuestionService.java
- resolve #50 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 질문 상세 조회 시 조회수 증가 기능 개발

src/main/java/team/onepoom/idk/common/exception/QuestionHasAnswersException.java, src/main/java/team/onepoom/idk/domain/question/Question.java, src/main/java/team/onepoom/idk/repository/CustomRepository.java, src/main/java/team/onepoom/idk/service/QuestionService.java
- resolve #52 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 질문 수정, 삭제 가능 여부 확인 기능

src/main/java/team/onepoom/idk/common/advice/SuspendDeniedAdvice.java, src/main/java/team/onepoom/idk/common/annotation/SuspendDenied.java, src/main/java/team/onepoom/idk/common/exception/QuestionReportNotFoundException.java, src/main/java/team/onepoom/idk/controller/QuestionController.java, src/main/java/team/onepoom/idk/controller/QuestionReportController.java, src/main/java/team/onepoom/idk/controller/UserController.java, src/main/java/team/onepoom/idk/domain/question/Question.java, src/main/java/team/onepoom/idk/domain/questionReport/QuestionReport.java, src/main/java/team/onepoom/idk/domain/questionReport/dto/CreateQuestionReportRequest.java, src/main/java/team/onepoom/idk/domain/questionReport/dto/GetQuestionReportResponse.java, src/main/java/team/onepoom/idk/domain/reportReason/ReportReason.java, src/main/java/team/onepoom/idk/repository/QuestionReportRepository.java, src/main/java/team/onepoom/idk/service/AnswerService.java, src/main/java/team/onepoom/idk/service/QuestionReportService.java, src/main/java/team/onepoom/idk/service/UserService.java, src/main/resources/questionreport.http
resolve #31
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 질문 신고기능 , 정지유저 접근제한 기능 추가

src/main/java/team/onepoom/idk/common/exception/SelectionConflictException.java, src/main/java/team/onepoom/idk/domain/answer/dto/AnswerResponse.java, src/main/java/team/onepoom/idk/domain/answer/dto/MyAnswerResponse.java, src/main/java/team/onepoom/idk/domain/user/dto/WriterDTO.java, src/main/java/team/onepoom/idk/service/AnswerService.java
resolve #55 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Fix] 답변 기능 수정(중복 채택 제한, 응답 수정)

src/main/java/team/onepoom/idk/common/exception/CompletedReportException.java, src/main/java/team/onepoom/idk/service/QuestionReportService.java
- resolve #56 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> feat(question): 질문 신고 처리/삭제 완료 여부 검증 후 중복 요청 막기

src/main/java/team/onepoom/idk/controller/NoticeController.java, src/main/java/team/onepoom/idk/repository/NoticeRepository.java, src/main/java/team/onepoom/idk/service/NoticeService.java, src/main/resources/notice.http
resolve #54 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> refactor(notice): 공지사항 최신 5개 조회 리스트로 반환

src/main/java/team/onepoom/idk/controller/AnswerReportController.java, src/main/java/team/onepoom/idk/domain/user/User.java, src/main/resources/answerreport.http
resolve #66 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Fix] 답변 신고 처리 기능 수정

src/main/java/team/onepoom/idk/controller/QuestionController.java
resolve #63 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] QuestionController 에 어노테이션 추가

src/main/java/team/onepoom/idk/domain/answer/dto/AnswerDTO.java, src/main/java/team/onepoom/idk/domain/answerReport/AnswerReport.java, src/main/java/team/onepoom/idk/domain/answerReport/dto/GetAnswerReportResponse.java, src/main/java/team/onepoom/idk/domain/questionReport/dto/GetQuestionReportResponse.java, src/main/java/team/onepoom/idk/service/AnswerReportService.java, src/main/resources/answerreport.http, src/main/resources/question.http, src/main/resources/questionreport.http
resolve #68
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Fix] 답변 신고 기능 수정

frontend/src/api/index.js, frontend/src/router/index.js, frontend/src/views/NoticeView.vue, frontend/src/views/QuestionEditView.vue, frontend/src/views/QuestionView.vue, src/main/java/team/onepoom/idk/controller/AnswerController.java, src/main/java/team/onepoom/idk/domain/answer/Answer.java, src/main/java/team/onepoom/idk/domain/answer/dto/CreateAnswerRequest.java, src/main/java/team/onepoom/idk/service/AnswerService.java
- resolve #84 
PR의 개요를 적어주세요.
- 공지사항 css 일부 수정
- 질문 수정/삭제 구현
- 질문 content pre태그로 수정
- 답변 작성 칸 auto resize 적용
- 답변 등록 코드 일부 수정
- 답변 등록 구현
=> [Feat] 질문 상세 페이지 추가 개발

src/main/java/team/onepoom/idk/controller/AnswerController.java, src/main/java/team/onepoom/idk/controller/NoticeController.java, src/main/java/team/onepoom/idk/controller/QuestionController.java, src/main/java/team/onepoom/idk/controller/ReportReasonController.java, src/main/java/team/onepoom/idk/controller/UserController.java, src/main/java/team/onepoom/idk/domain/reportReason/dto/CreateReportReasonRequest.java
=> [Fix] 유효성 검증 어노테이션 추가

frontend/src/api/index.js, frontend/src/views/NoticeListView.vue, src/main/java/team/onepoom/idk/domain/notice/dto/AllNoticeResponse.java, src/main/resources/notice.http
resolve #89 
PR의 개요를 적어주세요.
index.js에 
```js
const getNoticesAPI = function () {
return authInstance.get(`/api/notices`)
}
export 에
getNoticesAPI 추가했습니다 !
```
AllNoticeResponse에 공지사항 id 추가했어요 ~!
=> [Feat] 공지사항 목록 페이지 구현

frontend/src/App.vue, frontend/src/assets/yellow-dot.svg, frontend/src/views/HomeView.vue
resolve #75
PR의 개요를 적어주세요.
script 부분 나중에 다시 구현할 예정입니다.
=> [Feat] 메인페이지 구현

frontend/src/views/HomeView.vue, frontend/src/views/MyAnswersListView.vue
resolve #93
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 마이페이지 구현

frontend/src/api/index.js, frontend/src/router/index.js, frontend/src/views/QuestionView.vue, frontend/src/views/ReportAnswerModal.vue, frontend/src/views/ReportQuestionModal.vue, src/main/java/team/onepoom/idk/domain/reportReason/dto/AllReportReasonResponse.java, src/main/resources/questionreport.http
resolve #96 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 질문 신고 모달 구현

frontend/src/api/index.js, frontend/src/views/HomeView.vue, frontend/src/views/MyView.vue, src/main/java/team/onepoom/idk/domain/notice/dto/FiveNoticeResponse.java
- resolve #101 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 데이터 바인딩 및 버튼 이벤트 구현

frontend/src/App.vue, frontend/src/components/FooterComponent.vue, frontend/src/components/HeaderComponent.vue, frontend/src/router/index.js, frontend/src/views/HomeView.vue, frontend/src/views/NoticeView.vue, frontend/src/views/QuestionView.vue, frontend/src/views/SignupView.vue, src/main/java/team/onepoom/idk/common/advice/GlobalExceptionAdvice.java, src/main/java/team/onepoom/idk/common/exception/DuplicateEmailException.java, src/main/java/team/onepoom/idk/common/exception/DuplicateNicknameException.java, src/main/java/team/onepoom/idk/repository/UserRepository.java, src/main/java/team/onepoom/idk/service/UserService.java
- resolve #103 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 프론트엔드 추가 수정

src/main/java/team/onepoom/idk/repository/CustomRepository.java
- resolve #110 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> fix(question): 가려진 질문까지 카운트 되는 오류 수정

README.md
resolve #114
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> update 페이지 프리뷰 틀 작성

src/main/java/team/onepoom/idk/controller/AnswerReportController.java, src/main/java/team/onepoom/idk/domain/answerReport/AnswerReport.java, src/main/java/team/onepoom/idk/domain/answerReport/dto/GetAnswerReportResponse.java, src/main/java/team/onepoom/idk/domain/questionReport/QuestionReport.java, src/main/java/team/onepoom/idk/domain/questionReport/dto/CreateQuestionReportRequest.java, src/main/java/team/onepoom/idk/domain/questionReport/dto/GetQuestionReportResponse.java, src/main/java/team/onepoom/idk/service/AnswerReportService.java, src/main/java/team/onepoom/idk/service/QuestionReportService.java, src/main/resources/questionreport.http
resolve #106
버그 수정 
작업한 내용을 적어주세요.
데이터 베이스 구조 변경 필요합니다
=> [FIX] 신고사유 삭제 안되는 이슈

build.gradle
- resolve #124 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> build(gradle): 스프링 액츄에이터 의존성 추가

build.gradle
- resolve #124 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 스프링 액츄에이터 적용 #124

build.gradle, src/main/java/team/onepoom/idk/domain/answer/dto/AnswerDTO.java, src/main/java/team/onepoom/idk/service/AnswerService.java, src/test/java/team/onepoom/idk/controller/AnswerControllerTest.java, src/test/java/team/onepoom/idk/repository/AnswerRepositoryTest.java, src/test/java/team/onepoom/idk/service/AnswerServiceTest.java, src/test/java/team/onepoom/idk/util/TestSecurityContextFactory.java, src/test/resources/sql/answer-repository-test-data.sql
resolve #128 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Test] 답변기능 테스트 코드 작성

build.gradle, src/main/java/team/onepoom/idk/domain/answer/dto/AnswerDTO.java, src/main/java/team/onepoom/idk/service/AnswerService.java, src/test/java/team/onepoom/idk/controller/AnswerControllerTest.java, src/test/java/team/onepoom/idk/repository/AnswerRepositoryTest.java, src/test/java/team/onepoom/idk/service/AnswerServiceTest.java, src/test/java/team/onepoom/idk/util/TestSecurityContextFactory.java, src/test/resources/sql/answer-repository-test-data.sql
=> merge Develop

src/main/java/team/onepoom/idk/domain/question/Question.java
=> test(cicd): 서버 ip 변경 후 cicd 테스트

frontend/src/views/HomeView.vue, src/main/java/team/onepoom/idk/domain/question/dto/GetQuestionResponse.java, src/main/java/team/onepoom/idk/repository/CustomRepository.java
- resolve #145 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
=> [Feat] 성능 최적화

.github/workflows/deploy.yml, .github/workflows/pr-check.yml, Dockerfile, frontend/Dockerfile
=> ci: cicd 파이프라인 수정, 도커 파일 수정

.github/workflows/deploy.yml
=> ci: cicd 파이프라인 수정

src/main/java/team/onepoom/idk/IdkApplication.java
=> test: CI/CD 배포 시간 측정

.github/workflows/deploy.yml
=> ci: deploy 파이프라인 수정

Dockerfile
=> ci: 도커 이미지 최적화

.github/workflows/deploy.yml
=> ci: 깃 해시 버전 추가
